### ISSUE TITLE
mood generate

### ISSUE THREAD

**Issue by JensonChoi** [JensonChoi/moodify#1]
## Epic
Create a web application that allows users to input a mood (study, sad, happy) and generates a playlist based on the word. Users can save the playlist to their Spotify account and play the tracks generated using a web player.

## User Stories
- [x] #5 : user authentication
- [x] #6: UI for landing page
- [x] #7: basic scaffolding for website
- [x] #8 : UI for song generation page
- [x] #9 UI for results page
- [x] #10: UI for about page
- [x] #11 : generate playlist based on mood
- [x] #12: save playlist to user's Spotify library
- [x] #15: generate AI art as thumbnail
- [x] #22: deploy the app to Netlify
